### ISSUE TITLE
Eukcc Failure 

### ISSUE THREAD

**Issue by u15412611** [Finn-Lab/EukCC#16] opened 2021-01-25 10:12 UTC
Good day Thank you for such a great program
I have installed it on a linux system through conda env. I have tried to run it on a set of bins obtained via concoct. I get the following error. 

**_check before run
create directories
commit input data
soft_mask is in the 'auto' mode. soft_mask was set to: 1000
data report
commit training data
error, not enough sequnce to run training in file /home/percy/rep_contigs/contigs/Eukbins/eukb/workfiles/gmes/data/training.fna
	(in cleanup) Can't call method "FETCH" on an undefined value at /usr/local/share/perl5/Object/InsideOut.pm line 1953 during global destruction._**

please could you assist ?

**Comment by openpaul** [comment] 2021-01-25 15:39
Hello,
this seems like GeneMark-ES failed. Did you manage to run the minimal example from the documentation?
https://eukcc.readthedocs.io/en/latest/install.html#quickstart-and-testing

If GeneMark-ES fails, EukCC also fails. Your current best bet is then to run either GeneMark-ES manually or use some other form of protein prediction for Eukaryotes. 

Incomplete bins are often the cause of such failures.

**Comment by openpaul** [comment] 2021-02-01 12:31
I will close this for now, please reopen if you could not solve the issue.

**Closed by openpaul** 2021-02-01 12:31 UTC
